"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Paperclip, Send } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { z } from "zod";
const schema = z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().min(7), description: z.string().min(20), quantity: z.string(), material: z.string(), website: z.string() });
type Values = z.infer<typeof schema>;
export function CustomPartForm() { const [files, setFiles] = useState<File[]>([]); const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name:"",email:"",phone:"",description:"",quantity:"",material:"",website:"" } }); const submit = async (values: Values) => { const id = toast.loading("Submitting your request…"); const form = new FormData(); Object.entries(values).forEach(([key,value]) => form.append(key,value)); files.forEach((file) => form.append("files",file)); const response = await fetch("/api/custom-part-requests",{method:"POST",body:form}); const data = await response.json(); if (!response.ok) return toast.error(data.message || "Request could not be submitted.",{id}); toast.success(`Request CP-${data.orderNumber} submitted.`,{id}); reset(); setFiles([]); };
 return <section id="custom-part-request" className="scroll-mt-24"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-[#d5dad2] md:p-10"><p className="eyebrow">Request a custom part</p><h2 className="heading mt-4">Tell us what you need made.</h2><p className="mt-4 body-copy">Share the requirements and any reference or manufacturing files. We’ll contact you to discuss the next step.</p><form onSubmit={handleSubmit(submit)} className="mt-8 grid gap-5"><input className="hidden" tabIndex={-1} autoComplete="off" {...register("website")} /><div className="grid gap-5 md:grid-cols-2"><Field label="Name" error={errors.name?.message}><input className="input" {...register("name")} /></Field><Field label="Email" error={errors.email?.message}><input className="input" type="email" {...register("email")} /></Field><Field label="Phone number" error={errors.phone?.message}><input className="input" type="tel" {...register("phone")} /></Field><Field label="Quantity"><input className="input" {...register("quantity")} /></Field><Field label="Material preference"><input className="input" placeholder="Optional" {...register("material")} /></Field></div><Field label="Part description" error={errors.description?.message}><textarea className="input" rows={6} {...register("description")} /></Field><div><label className="button button-ghost cursor-pointer"><Paperclip size={16}/> Attach files<input className="sr-only" type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif,.3mf,.stl,.step,.stp,.pdf,.zip" onChange={(event) => { const picked=Array.from(event.target.files||[]); if (picked.length+files.length>10 || picked.some((file)=>file.size>50*1024*1024)) return toast.error("Up to 10 files, maximum 50 MB each."); setFiles((current)=>[...current,...picked]); event.target.value=""; }} /></label><p className="mt-2 text-xs text-[#61706b]">Images, 3MF, STL, STEP, PDF or ZIP. Up to 10 files, 50 MB each.</p><div className="mt-3 flex flex-wrap gap-2">{files.map((file,index)=><button type="button" key={`${file.name}-${index}`} onClick={()=>setFiles((current)=>current.filter((_file,i)=>i!==index))} className="rounded-full bg-[#edf0ea] px-3 py-1.5 text-xs font-bold">{file.name} ×</button>)}</div></div><button disabled={isSubmitting} className="button button-dark w-fit"><Send size={16}/>{isSubmitting?"Submitting…":"Submit request"}</button></form></div></section>; }
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div><label className="label">{label}</label>{children}{error&&<p className="error">{error}</p>}</div>}
