import { readFile } from 'node:fs/promises';
import path from "node:path";
import { Pool } from "pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is not configured.");

const database = new Pool({ connectionString, max: 1 });

async function loadJson(fileName) {
  try {
    return JSON.parse(await readFile(path.join(process.cwd(), "data", fileName), "utf8"));
  } catch {
    return [];
  }
}

async function main() {
  await database.query(`
    CREATE TABLE IF NOT EXISTS projects (
      id text PRIMARY KEY,
      slug text UNIQUE NOT NULL,
      kind text NOT NULL CHECK (kind IN ('industry', 'printing')),
      title text NOT NULL,
      summary text NOT NULL,
      description text NOT NULL,
      image text NOT NULL,
      images jsonb NOT NULL DEFAULT '[]'::jsonb,
      videos jsonb NOT NULL DEFAULT '[]'::jsonb,
      tags jsonb NOT NULL DEFAULT '[]'::jsonb,
      featured boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS custom_part_requests (
      id text PRIMARY KEY,
      order_number integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE NOT NULL,
      name text NOT NULL,
      email text NOT NULL,
      phone text NOT NULL,
      description text NOT NULL,
      quantity text,
      material text,
      files jsonb NOT NULL DEFAULT '[]'::jsonb,
      status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'quoted', 'closed')),
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS projects_kind_created_at_idx ON projects (kind, created_at DESC);
    CREATE INDEX IF NOT EXISTS custom_part_requests_created_at_idx ON custom_part_requests (created_at DESC);
  `);

  const projects = await loadJson("projects.json");
  for (const project of projects) {
    await database.query(
      `INSERT INTO projects (id, slug, kind, title, summary, description, image, images, videos, tags, featured, created_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11,$12)
       ON CONFLICT (id) DO NOTHING`,
      [project.id, project.slug, project.kind, project.title, project.summary, project.description, project.image, JSON.stringify(project.images?.length ? project.images : [project.image]), JSON.stringify(project.videos || []), JSON.stringify(project.tags || []), project.featured, project.createdAt],
    );
  }

  const requests = await loadJson("custom-part-requests.json");
  for (const request of requests) {
    await database.query(
      `INSERT INTO custom_part_requests (id, name, email, phone, description, quantity, material, files, status, created_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)
       ON CONFLICT (id) DO NOTHING`,
      [request.id, request.name, request.email, request.phone, request.description, request.quantity || null, request.material || null, JSON.stringify(request.files || []), request.status || "new", request.createdAt],
    );
  }

  const counts = await database.query("SELECT (SELECT count(*) FROM projects)::int AS projects, (SELECT count(*) FROM custom_part_requests)::int AS requests");
  console.log(`Database ready: ${counts.rows[0].projects} projects, ${counts.rows[0].requests} custom-part requests.`);
}

main().finally(() => database.end());
