import { Pool } from "pg";
import "./load-local-env.mjs";

const sourceConnectionString = process.env.SOURCE_DATABASE_URL;
const destinationConnectionString = process.env.DESTINATION_DATABASE_URL;

if (!sourceConnectionString) throw new Error("SOURCE_DATABASE_URL is not configured.");
if (!destinationConnectionString) throw new Error("DESTINATION_DATABASE_URL is not configured.");
if (sourceConnectionString === destinationConnectionString) {
  throw new Error("Source and destination databases must be different.");
}

const source = new Pool({ connectionString: sourceConnectionString, max: 1 });
const destination = new Pool({ connectionString: destinationConnectionString, max: 1 });

async function createSchema(client) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS projects (
      id text PRIMARY KEY,
      slug text UNIQUE NOT NULL,
      kind text NOT NULL CHECK (kind IN ('industry', 'printing')),
      title text NOT NULL,
      summary text NOT NULL,
      description text NOT NULL,
      image text NOT NULL,
      images jsonb NOT NULL DEFAULT '[]'::jsonb,
      videos jsonb NOT NULL DEFAULT '[]'::jsonb,
      tags jsonb NOT NULL DEFAULT '[]'::jsonb,
      featured boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS custom_part_requests (
      id text PRIMARY KEY,
      order_number integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE NOT NULL,
      name text NOT NULL,
      email text NOT NULL,
      phone text NOT NULL,
      description text NOT NULL,
      quantity text,
      material text,
      files jsonb NOT NULL DEFAULT '[]'::jsonb,
      status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'quoted', 'closed')),
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS projects_kind_created_at_idx ON projects (kind, created_at DESC);
    CREATE INDEX IF NOT EXISTS custom_part_requests_created_at_idx ON custom_part_requests (created_at DESC);
  `);
}

async function main() {
  const [projects, requests] = await Promise.all([
    source.query("SELECT * FROM projects ORDER BY created_at"),
    source.query("SELECT * FROM custom_part_requests ORDER BY created_at"),
  ]);

  const client = await destination.connect();
  try {
    await client.query("BEGIN");
    await createSchema(client);

    for (const project of projects.rows) {
      await client.query(
        `INSERT INTO projects (id, slug, kind, title, summary, description, image, images, videos, tags, featured, created_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11,$12)
         ON CONFLICT (id) DO UPDATE SET
           slug=EXCLUDED.slug, kind=EXCLUDED.kind, title=EXCLUDED.title,
           summary=EXCLUDED.summary, description=EXCLUDED.description,
           image=EXCLUDED.image, images=EXCLUDED.images, videos=EXCLUDED.videos,
           tags=EXCLUDED.tags, featured=EXCLUDED.featured, created_at=EXCLUDED.created_at`,
        [project.id, project.slug, project.kind, project.title, project.summary,
          project.description, project.image, JSON.stringify(project.images),
          JSON.stringify(project.videos), JSON.stringify(project.tags),
          project.featured, project.created_at],
      );
    }

    for (const request of requests.rows) {
      await client.query(
        `INSERT INTO custom_part_requests
           (id, order_number, name, email, phone, description, quantity, material, files, status, created_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)
         ON CONFLICT (id) DO UPDATE SET
           order_number=EXCLUDED.order_number, name=EXCLUDED.name, email=EXCLUDED.email,
           phone=EXCLUDED.phone, description=EXCLUDED.description, quantity=EXCLUDED.quantity,
           material=EXCLUDED.material, files=EXCLUDED.files, status=EXCLUDED.status,
           created_at=EXCLUDED.created_at`,
        [request.id, request.order_number, request.name, request.email, request.phone,
          request.description, request.quantity, request.material,
          JSON.stringify(request.files), request.status, request.created_at],
      );
    }

    await client.query(`
      SELECT setval(
        pg_get_serial_sequence('custom_part_requests', 'order_number'),
        MAX(order_number),
        true
      )
      FROM custom_part_requests
      HAVING COUNT(*) > 0
    `);
    await client.query("COMMIT");
    console.log(`Transferred ${projects.rowCount} projects and ${requests.rowCount} custom-part requests.`);
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

main().finally(async () => {
  await Promise.all([source.end(), destination.end()]);
});
